In [1]:

import pandas as pd
import numpy as np
from scipy import stats

In [2]:

df = pd.read_csv('market_data/BARC.L.csv')
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2013-09-16,282.665985,286.269012,278.001007,282.112000,250.591934,53489132
1,2013-09-17,281.927002,282.204010,273.013000,276.200012,245.340515,73143097
2,2013-09-18,284.000000,297.295013,275.350006,277.200012,246.228760,75208440
3,2013-09-19,282.200012,282.200012,277.500000,278.299988,247.205795,81062189
4,2013-09-20,277.850006,277.950012,272.700012,273.450012,242.897705,99305712
5,2013-09-23,271.799988,272.035004,265.000000,266.350006,236.590988,102546928
6,2013-09-24,265.899994,273.595001,265.700012,271.450012,241.121170,87499240
7,2013-09-25,271.799988,277.656006,270.350006,273.000000,242.497971,82996400
8,2013-09-26,274.000000,274.200012,265.000000,269.200012,239.122543,74870176
9,2013-09-27,268.350006,269.750000,263.950012,265.799988,236.102417,82937528
10,2013-09-30,262.100006,266.227997,261.250000,265.500000,235.835922,52602640
11,2013-10-01,266.950012,272.122986,264.000000,269.799988,239.655487,53101816
12,2013-10-02,271.000000,274.549988,268.700012,272.549988,242.098206,43893800
13,2013-10-03,272.000000,275.500000,271.450012,273.000000,242.497971,32607288
14,2013-10-04,271.600006,274.250000,268.000000,271.350006,241.032333,67264805
15,2013-10-07,272.000000,273.615997,267.295990,272.549988,242.098206,37428296
16,2013-10-08,271.700012,274.100006,267.700012,268.200012,238.234299,40445504
17,2013-10-09,266.850006,272.000000,265.588013,267.799988,237.878983,33716048
18,2013-10-10,269.450012,275.269989,267.850006,274.500000,243.830399,57356160
19,2013-10-11,276.950012,280.489990,273.700012,278.000000,246.939346,42782992
20,2013-10-14,276.600006,279.989990,274.459991,276.850006,245.917862,28034836
21,2013-10-15,279.649994,281.790009,277.860992,279.850006,248.582611,37613464
22,2013-10-16,278.500000,285.580994,277.863007,283.649994,251.958084,45641647
23,2013-10-17,281.399994,281.739990,275.036011,278.299988,247.205795,72355949
24,2013-10-18,279.049988,280.342010,272.200012,277.850006,246.806107,84387120
25,2013-10-21,277.049988,277.279999,272.149994,274.750000,244.052444,36149417
26,2013-10-22,274.399994,276.950012,272.243988,272.600006,242.142639,39629712
27,2013-10-23,274.100006,274.500000,266.399994,268.200012,238.234299,73910032
28,2013-10-24,269.000000,271.268005,265.600006,266.450012,236.679840,48381752
29,2013-10-25,266.049988,271.971985,265.149994,267.899994,237.967834,46775000
...,...,...,...,...,...,...,...
1234,2018-08-02,197.500000,197.500000,185.179993,186.539993,184.125183,195187405
1235,2018-08-03,186.940002,190.940002,186.940002,188.699997,186.257217,45961471
1236,2018-08-06,188.899994,189.419998,186.839996,188.559998,186.119034,181057065
1237,2018-08-07,188.559998,190.240005,187.000000,189.360001,186.908676,35712022
1238,2018-08-08,189.259995,193.600006,189.100006,193.119995,190.619995,45918718
1239,2018-08-09,191.339996,191.720001,189.220001,191.500000,191.500000,31744420
1240,2018-08-10,190.380005,190.559998,186.080002,187.639999,187.639999,41570399
1241,2018-08-13,186.559998,187.440002,184.440002,184.500000,184.500000,35928796
1242,2018-08-14,184.820007,185.520004,183.300003,183.960007,183.960007,65386513
1243,2018-08-15,185.179993,185.259995,179.240005,179.800003,179.800003,94325775
1244,2018-08-16,180.600006,182.419998,180.000000,182.179993,182.179993,37612805
1245,2018-08-17,182.360001,184.179993,181.539993,182.600006,182.600006,24124066
1246,2018-08-20,183.179993,185.020004,182.839996,183.720001,183.720001,28754161
1247,2018-08-21,182.779999,185.339996,182.699997,184.399994,184.399994,28271396
1248,2018-08-22,183.880005,185.899994,183.759995,185.199997,185.199997,31380373
1249,2018-08-23,185.360001,185.660004,183.139999,183.139999,183.139999,48603130
1250,2018-08-24,182.360001,185.000000,182.360001,183.660004,183.660004,27437058
1251,2018-08-28,185.000000,185.539993,182.940002,183.699997,183.699997,27523590
1252,2018-08-29,183.539993,183.979996,180.039993,181.440002,181.440002,38206958
1253,2018-08-30,181.380005,181.380005,178.199997,178.300003,178.300003,39664086
1254,2018-08-31,178.800003,178.880005,175.179993,175.699997,175.699997,55999433
1255,2018-09-03,176.899994,177.800003,176.240005,177.520004,177.520004,42328205
1256,2018-09-04,178.720001,181.100006,178.000000,181.020004,181.020004,46907935
1257,2018-09-05,180.240005,180.559998,177.740005,178.000000,178.000000,87522028
1258,2018-09-06,177.740005,178.639999,175.940002,176.199997,176.199997,56094829
1259,2018-09-07,176.220001,176.279999,172.419998,174.500000,174.500000,55377621
1260,2018-09-10,174.639999,177.259995,173.500000,176.800003,176.800003,108272589
1261,2018-09-11,176.580002,176.800003,173.699997,174.740005,174.740005,46928387
1262,2018-09-12,174.500000,174.740005,171.740005,172.220001,172.220001,44363997
1263,2018-09-13,172.639999,174.320007,171.740005,172.199997,172.199997,37694060

In [3]:

close_series = df['Adj Close']
close_series[:10]

0    250.591934
1    245.340515
2    246.228760
3    247.205795
4    242.897705
5    236.590988
6    241.121170
7    242.497971
8    239.122543
9    236.102417
Name: Adj Close, dtype: float64

In [4]:


#df['log_ret'] = np.log(df.price) - np.log(df.price.shift(1))
log_returns = np.log(close_series) - np.log(close_series.shift(1)) # -1 * 100
#log_returns.dropna(inplace=True)
        
log_returns[:10]

0         NaN
1   -0.021179
2    0.003614
3    0.003960
4   -0.017581
5   -0.026308
6    0.018967
7    0.005694
8   -0.014017
9   -0.012710
Name: Adj Close, dtype: float64

In [5]:

df.Date = pd.to_datetime(df.Date)
df.set_index('Date', inplace=True)

In [11]:

df['Log Ret'] = np.log(df['Adj Close']) - np.log(df['Adj Close'].shift(1))

monthly = df.resample('BM').apply(lambda x: x[-1]) # use BA for business annual (year)
monthly

,Open,High,Low,Close,Adj Close,Volume,Log Ret
Date,,,,,,,
2013-09-30,262.100006,266.227997,261.250000,265.500000,235.835922,52602640,-0.001129
2013-10-31,267.649994,272.000000,261.600006,263.600006,234.148270,75351520,-0.018232
2013-11-29,266.149994,274.860992,265.899994,271.700012,242.316406,78795663,0.022707
2013-12-31,271.549988,274.299988,271.049988,271.950012,242.539352,12174455,0.003130
2014-01-31,274.350006,274.399994,267.549988,272.500000,243.029846,49273966,-0.009314
2014-02-28,254.399994,255.000000,251.250000,252.100006,227.888550,58789772,-0.007115
2014-03-31,231.899994,233.750000,231.100006,233.399994,210.984482,69418299,0.009903
2014-04-30,249.800003,253.104004,248.110001,252.199997,227.978943,38563163,0.007762
2014-05-30,246.500000,247.089996,243.968002,247.000000,224.156158,86089262,0.003853
2014-06-30,217.100006,220.268005,211.800003,212.800003,193.119156,55673986,-0.015157
2014-07-31,227.399994,229.212997,225.199997,225.699997,204.826111,54296486,-0.011892
2014-08-29,224.149994,226.199997,222.949997,224.449997,204.613831,29719811,0.001784
2014-09-30,226.750000,229.949997,226.449997,227.449997,207.348709,40063161,0.006396
2014-10-31,224.800003,245.149994,223.350006,240.800003,219.518875,184917553,0.078815
2014-11-28,243.000000,246.500000,242.800003,245.149994,224.427200,33525052,0.005522
2014-12-31,242.500000,244.649994,241.621002,243.500000,222.916656,8019207,0.008662
2015-01-30,237.750000,239.350006,234.149994,234.149994,214.357025,30434587,-0.010198
2015-02-27,261.000000,263.700012,256.000000,256.899994,235.183945,41803803,-0.020039
2015-03-31,248.500000,248.500000,242.000000,242.600006,225.091690,46741243,-0.021208
2015-04-30,258.100006,258.200012,252.800003,255.300003,236.875137,38686597,-0.006442
2015-05-29,270.149994,272.000000,267.950012,270.000000,251.522583,39224439,-0.004066
2015-06-30,262.500000,265.299988,260.500000,260.500000,242.672668,48682385,-0.014293
2015-07-31,287.500000,289.450012,286.350006,288.950012,269.175720,40987558,0.006597
2015-08-31,260.500000,263.450012,257.750000,261.450012,244.424454,43554775,-0.004389
2015-09-30,243.500000,247.209000,243.000000,244.149994,228.251007,40715567,0.021319
2015-10-30,234.000000,236.335007,230.699997,232.000000,216.892197,60170767,-0.022377
2015-11-30,223.500000,224.500000,221.500000,223.199997,209.567230,27498730,-0.004916
2015-12-31,220.000000,220.000000,217.550003,218.899994,205.529861,5181681,-0.008189
2016-01-29,181.350006,186.000000,180.550003,186.000000,174.639359,57835626,0.041719
2016-02-29,167.850006,172.914001,166.119003,172.050003,161.541412,55849036,0.017295
...,...,...,...,...,...,...,...
2016-04-29,171.800003,174.850006,171.250000,171.500000,164.446884,63013667,-0.016768
2016-05-31,186.550003,188.149994,181.529999,182.399994,174.898621,47907064,-0.020619
2016-06-30,138.000000,139.350006,134.350006,138.600006,132.899948,100950677,0.004701
2016-07-29,150.449997,159.850006,147.143997,154.550003,148.193970,114349697,0.053492
2016-08-31,169.449997,175.000000,169.199997,172.250000,166.181213,60135714,0.018161
2016-09-30,162.899994,167.800003,155.949997,167.800003,161.888000,117264694,0.002984
2016-10-31,190.199997,191.699997,188.899994,190.300003,183.595291,40797797,-0.005241
2016-11-30,213.449997,216.899994,211.850006,215.949997,208.341568,47668673,0.007903
2016-12-30,221.350006,223.449997,220.082993,223.449997,215.577316,15871501,0.004935
2017-01-31,222.800003,226.050003,219.100006,219.449997,211.718246,48441418,-0.017839
2017-02-28,224.500000,227.449997,222.750000,226.500000,218.519852,67908759,0.006645
2017-03-31,227.800003,227.949997,225.087997,225.100006,219.050247,47777985,-0.013020
2017-04-28,213.000000,218.091003,207.750000,212.250000,206.545609,99386155,-0.053658
2017-05-31,209.199997,215.404999,206.600006,210.000000,204.356079,79506925,0.003817
2017-06-30,205.949997,207.149994,202.000000,202.750000,197.300919,5096293,-0.013472
2017-07-31,203.949997,206.399994,201.199997,203.000000,197.544205,50907891,-0.010292
2017-08-31,191.500000,192.250000,190.000000,191.100006,186.859177,32271117,0.002095
2017-09-29,192.750000,194.050003,191.500000,193.350006,189.059235,28016234,0.005966
2017-10-31,184.399994,186.649994,183.690002,185.949997,181.823441,58150594,0.013263
2017-11-30,193.699997,195.750000,191.699997,193.500000,189.205902,72175125,-0.003868
2017-12-29,203.250000,203.850006,201.850006,203.100006,198.592865,15181039,-0.001476
2018-01-31,203.300003,204.199997,199.139999,199.940002,195.502975,53613477,-0.009012
2018-02-28,210.949997,215.800003,210.899994,213.500000,208.762070,81046305,0.007051
2018-03-30,207.100006,208.250000,204.149994,206.500000,203.826797,64604049,0.002424
2018-04-30,208.800003,209.449997,206.949997,207.250000,204.567093,57926034,-0.008169
2018-05-31,199.699997,201.050003,196.259995,197.240005,194.686676,66922727,-0.009788
2018-06-29,191.839996,193.100006,188.880005,189.000000,186.553345,40829966,-0.004856
2018-07-31,192.740005,196.119995,192.419998,193.960007,191.449142,35121549,0.005169
2018-08-31,178.800003,178.880005,175.179993,175.699997,175.699997,55999433,-0.014690
2018-09-28,172.639999,174.320007,171.740005,172.199997,172.199997,37694060,-0.000116

In [7]:

monthly.pct_change()

,Open,High,Low,Close,Adj Close,Volume,Log Ret
Date,,,,,,,
2013-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-10-31,0.021175,0.021681,0.001340,-0.007156,-0.007156,0.432467,15.143399
2013-11-29,-0.005604,0.010518,0.016437,0.030728,0.034884,0.045708,-2.245481
2013-12-31,0.020289,-0.002041,0.019368,0.000920,0.000920,-0.845493,-0.862139
2014-01-31,0.010311,0.000365,-0.012913,0.002022,0.002022,3.047324,-3.975368
2014-02-28,-0.072717,-0.070700,-0.060923,-0.074862,-0.062302,0.193120,-0.236151
2014-03-31,-0.088443,-0.083333,-0.080199,-0.074177,-0.074177,0.180789,-2.391943
2014-04-30,0.077188,0.082798,0.073604,0.080548,0.080548,-0.444481,-0.216221
2014-05-30,-0.013211,-0.023761,-0.016694,-0.020619,-0.016768,1.232422,-0.503541
2014-06-30,-0.119270,-0.108552,-0.131853,-0.138462,-0.138462,-0.353299,-4.933379
2014-07-31,0.047444,0.040610,0.063267,0.060620,0.060620,-0.024742,-0.215444
2014-08-29,-0.014292,-0.013145,-0.009991,-0.005538,-0.001036,-0.452638,-1.150000
2014-09-30,0.011599,0.016578,0.015699,0.013366,0.013366,0.348029,2.585425
2014-10-31,-0.008600,0.066101,-0.013690,0.058694,0.058694,3.615651,11.323472
2014-11-28,0.080961,0.005507,0.087083,0.018065,0.022359,-0.818703,-0.929936
2014-12-31,-0.002058,-0.007505,-0.004856,-0.006731,-0.006731,-0.760800,0.568539
2015-01-30,-0.019588,-0.021664,-0.030920,-0.038398,-0.038398,2.795212,-2.177356
2015-02-27,0.097792,0.101734,0.093316,0.097160,0.097160,0.373562,0.965067
2015-03-31,-0.047893,-0.057641,-0.054688,-0.055664,-0.042912,0.118110,0.058322
2015-04-30,0.038632,0.039034,0.044628,0.052350,0.052350,-0.172324,-0.696236
2015-05-29,0.046687,0.053447,0.059929,0.057579,0.061836,0.013903,-0.368875
2015-06-30,-0.028318,-0.024632,-0.027804,-0.035185,-0.035185,0.241124,2.515344
2015-07-31,0.095238,0.091029,0.099232,0.109213,0.109213,-0.158062,-1.461580
2015-08-31,-0.093913,-0.089826,-0.099878,-0.095172,-0.091952,0.062634,-1.665261
2015-09-30,-0.065259,-0.061647,-0.057226,-0.066170,-0.066170,-0.065187,-5.857477
2015-10-30,-0.039014,-0.043987,-0.050617,-0.049764,-0.049765,0.477832,-2.049632
2015-11-30,-0.044872,-0.050077,-0.039879,-0.037931,-0.033772,-0.542989,-0.780301
2015-12-31,-0.015660,-0.020045,-0.017833,-0.019265,-0.019265,-0.811567,0.665754
2016-01-29,-0.175682,-0.154545,-0.170076,-0.150297,-0.150297,10.161557,-6.094299
2016-02-29,-0.074442,-0.070355,-0.079928,-0.075000,-0.075000,-0.034349,-0.585437
...,...,...,...,...,...,...,...
2016-04-29,0.135117,0.147686,0.154754,0.143333,0.143333,0.155140,0.532780
2016-05-31,0.085856,0.076065,0.060029,0.063557,0.063557,-0.239735,0.229663
2016-06-30,-0.260252,-0.259367,-0.259902,-0.240132,-0.240132,1.107219,-1.227982
2016-07-29,0.090217,0.147112,0.095229,0.115079,0.115079,0.132728,10.379255
2016-08-31,0.126288,0.094776,0.149894,0.114526,0.121376,-0.474107,-0.660491
2016-09-30,-0.038654,-0.041143,-0.078310,-0.025835,-0.025835,0.950001,-0.835690
2016-10-31,0.167588,0.142431,0.211286,0.134088,0.134088,-0.652088,-2.756323
2016-11-30,0.122240,0.131455,0.121493,0.134787,0.134787,0.168413,-2.508003
2016-12-30,0.037011,0.030198,0.038862,0.034730,0.034730,-0.667045,-0.375593
2017-01-31,0.006551,0.011636,-0.004466,-0.017901,-0.017901,2.052101,-4.614947
2017-02-28,0.007630,0.006193,0.016659,0.032126,0.032126,0.401874,-1.372462
2017-03-31,0.014699,0.002198,0.010496,-0.006181,0.002427,-0.296439,-2.959544
2017-04-28,-0.064969,-0.043251,-0.077028,-0.057086,-0.057086,1.080166,3.121122
2017-05-31,-0.017840,-0.012316,-0.005535,-0.010601,-0.010601,-0.200020,-1.071132
2017-06-30,-0.015535,-0.038323,-0.022265,-0.034524,-0.034524,-0.935901,-4.529745
2017-07-31,-0.009711,-0.003621,-0.003960,0.001233,0.001233,8.989200,-0.236084
2017-08-31,-0.061044,-0.068556,-0.055666,-0.058621,-0.054089,-0.366088,-1.203604
2017-09-29,0.006527,0.009363,0.007895,0.011774,0.011774,-0.131848,1.846938
2017-10-31,-0.043320,-0.038135,-0.040783,-0.038273,-0.038273,1.075604,1.223267
2017-11-30,0.050434,0.048754,0.043606,0.040602,0.040602,0.241176,-1.291670
2017-12-29,0.049303,0.041379,0.052947,0.049612,0.049612,-0.789664,-0.618478
2018-01-31,0.000246,0.001717,-0.013426,-0.015559,-0.015559,2.531608,5.106101
2018-02-28,0.037629,0.056807,0.059054,0.067820,0.067820,0.511678,-1.782348
2018-03-30,-0.018251,-0.034986,-0.032006,-0.032787,-0.023641,-0.202875,-0.656160
2018-04-30,0.008209,0.005762,0.013715,0.003632,0.003632,-0.103368,-4.369743
2018-05-31,-0.043582,-0.040105,-0.051655,-0.048299,-0.048299,0.155313,0.198121
2018-06-29,-0.039359,-0.039542,-0.037603,-0.041777,-0.041777,-0.389894,-0.503876
2018-07-31,0.004691,0.015640,0.018742,0.026243,0.026243,-0.139809,-2.064499
2018-08-31,-0.072325,-0.087905,-0.089596,-0.094143,-0.082263,0.594447,-3.841822
2018-09-28,-0.034452,-0.025492,-0.019637,-0.019920,-0.019920,-0.326885,-0.992092